add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", { outputdir = ".vscode" })
set_defaultmode("debug")
-- set_policy("build.c++.modules.non_cascading_changes", true)
-- set_policy("build.c++.modules.reuse.strict", true)
-- set_policy("build.progress_style", "multirow")

add_cxxflags("-fno-rtti", { tools = { "clang", "gcc" }})
add_cxxflags("/GR-", { tools = { "clang_cl", "cl" }})
set_languages("c++latest")
set_exceptions("no-cxx")
set_warnings("allextra")
set_rundir("$(projectdir)")

target("carven-modules")
    set_kind("moduleonly")
    add_files("src/**.cppm")

target("carven")
    add_deps("carven-modules")
    add_files("src/carven.cpp")

target("carven-test")
    add_deps("carven-modules")
    add_defines("DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS")
    add_files("tests/test_*.cpp")
