add_rules("mode.debug", "mode.release")
set_defaultmode("debug")
-- add_rules("plugin.compile_commands.autoupdate", { outputdir = ".vscode" })
-- set_policy("build.c++.modules.non_cascading_changes", true)
-- set_policy("build.c++.modules.reuse.strict", true)
-- set_policy("build.progress_style", "multirow")

add_cxxflags("-fno-rtti", { tools = { "clang", "gcc" } })
add_cxxflags("/D_HAS_EXCEPTIONS=0", "/D_CRT_SECURE_NO_WARNINGS", { tools = { "clang_cl", "cl" } })
add_cxxflags("/GR-", { tools = { "clang_cl", "cl" } })
add_cxxflags("-Wno-c23-extensions", { tools = { "clang", "gcc" } })
set_languages("c++latest")
set_exceptions("no-cxx")
set_warnings("allextra")
set_rundir("$(projectdir)")

target("carven-modules")
    set_kind("moduleonly")
    add_files("src/**.cppm")

target("carven")
    add_deps("carven-modules")
    add_files("src/carven.cpp")

target("carven-unit-test")
    set_default(false)
    add_deps("carven-modules")
    add_files("tests/units/test_*.cpp")
