add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", { outputdir = ".vscode" })
set_defaultmode("debug")
-- set_policy("build.c++.modules.non_cascading_changes", true)
-- set_policy("build.c++.modules.reuse.strict", true)
-- set_policy("build.progress_style", "multirow")

add_cxxflags("-fno-rtti", { tools = { "clang", "gcc" }})
add_cxxflags("/GR-", { tools = { "clang_cl", "cl" }})
set_languages("c++latest")
set_exceptions("no-cxx")
set_warnings("allextra")
set_rundir("$(projectdir)")

target("carven-modules")
    set_default(false)
    set_kind("moduleonly")
    add_files("src/**.cppm")

target("carven")
    add_deps("carven-modules")
    add_files("src/carven.cpp")
    add_installfiles("(xmake/rules/*.lua)", {prefixdir = "share/carven"})

target("carven-unit-test")
    set_default(false)
    add_deps("carven-modules")
    add_files("tests/test_main.cpp")
    add_files("tests/test_codegen.cpp")
    add_files("tests/test_common.cpp")
    add_files("tests/test_driver_handler.cpp")
    add_files("tests/test_dump.cpp")
    add_files("tests/test_filesystem.cpp")
    add_files("tests/test_golden.cpp")
    add_files("tests/test_lexer.cpp")
    add_files("tests/test_parser.cpp")
    add_files("tests/test_pipeline_flags.cpp")
    add_files("tests/test_pipeline_transpile.cpp")
    add_files("tests/test_sema.cpp")
    add_files("tests/test_toolchain.cpp")

target("carven-e2e-test")
    set_default(false)
    add_deps("carven", {inherit = false})
    add_deps("carven-modules")
    local bindir = "$(projectdir)/build/$(plat)/$(arch)/$(mode)"
    local carven_program = path.join(bindir, is_plat("windows") and "carven.exe" or "carven")
    local e2e_home = path.join(os.tmpdir(), "carven-e2e-home")
    add_runenvs("PATH", bindir)
    add_runenvs("CARVEN_E2E_CARVEN", carven_program)
    add_runenvs("HOME", e2e_home)
    add_runenvs("LOCALAPPDATA", e2e_home)
    add_runenvs("XDG_CACHE_HOME", e2e_home)
    add_files("tests/test_main.cpp")
    add_files("tests/test_e2e.cpp")
