module carven:diagnostics.code;

import std;

enum class DiagnosticSeverity {
    Error,
    Warning,
};

struct DiagnosticCodeInfo final {
    std::string_view name;
    DiagnosticSeverity default_severity;
    std::string_view description;
};

enum class DiagnosticCode {
    Invalid,
    AccessCallMismatch,
    AccessBorrowConflict,
    AccessCaptureConflict,
    AccessExpression,
    AccessOperationConflict,
    AccessTakeOperand,
    AccessUnavailable,
    AccessWriteArgument,
    AccessImmutable,
    AccessNotAssignable,
    AccessRangeBinding,
    AccessRangeIterable,
    AccessViewRangeBinding,
    Catalog,
    CompilationInput,
    CppBoundary,
    CppBoundaryType,
    CppIdentifier,
    CppAPIPathCollision,
    ConstArrayExtent,
    ConstCycle,
    ConstDivideByZero,
    ConstEnumCase,
    ConstEnumOverflow,
    ConstEnumRange,
    ConstExportedType,
    ConstInitializer,
    ConstIndexBounds,
    ConstLiteralRange,
    ConstNegativeArrayExtent,
    ConstOverflow,
    ConstShiftRange,
    EntryDuplicate,
    EntryParameters,
    FlowBreakOutsideLoop,
    FlowContinueOutsideLoop,
    FlowMissingReturn,
    FlowTransferValueBranch,
    FlowUnreachable,
    FlowUnreachableMatchArm,
    FlowValueBranchResult,
    ImportResolution,
    Lexical,
    LambdaCaptureMissing,
    LambdaCaptureDuplicate,
    LambdaCaptureInvalid,
    LambdaCaptureUnused,
    LambdaSignatureInference,
    LintUnusedImport,
    LintUnusedLocal,
    LintUnusedParameter,
    MatchDuplicateAlternative,
    MatchNonExhaustive,
    MatchBindingMismatch,
    NameAmbiguous,
    NameDuplicateEnumCase,
    NameDuplicateField,
    NameDuplicateLocal,
    NameDuplicateParameter,
    NameUnresolved,
    NameUnresolvedPattern,
    ParseNestingTooDeep,
    PointerNonNull,
    Syntax,
    EffectThrowType,
    EffectThrowDuplicate,
    EffectThrowPublished,
    EffectSignatureBound,
    EffectUnmarked,
    EffectPropagateRedundant,
    EffectRootUnhandled,
    EffectCatchNonExhaustive,
    EffectCatchArmUnreachable,
    EffectCatchAlternativeUnreachable,
    EffectRethrowContext,
    TestArgumentCount,
    TestConditionType,
    TestDuplicateName,
    TestMainName,
    TestMessageType,
    TypeArrayElement,
    TypeAssignmentInteger,
    TypeAssignmentNumeric,
    TypeBinary,
    TypeBinaryInteger,
    TypeBinaryNumeric,
    TypeBinaryOrdered,
    TypeCallArgument,
    TypeCallArity,
    TypeCallableViewEscape,
    TypeCast,
    TypeConditionBool,
    TypeConstructArity,
    TypeConstructDuplicateField,
    TypeConstructField,
    TypeConstructNotStruct,
    TypeConstructUnknownField,
    TypeEmptyArray,
    TypeEnumUnderlying,
    TypeEnumEmpty,
    TypeEnumProfile,
    TypeEnumDuplicateCode,
    TypeEnumCaseArity,
    TypeEnumContext,
    TypeEqualityUnsupported,
    TypeRecursiveStorage,
    TypeVisibilityLeak,
    TypeIfBranch,
    TypeIfMissingElse,
    TypeIndexInteger,
    TypeLogicalBool,
    TypeMatchArm,
    TypeMatchConstraint,
    TypeMatchPattern,
    TypeMemberUnresolved,
    TypeMismatch,
    TypeMissingReturnValue,
    TypeNotCallable,
    TypeNotIndexable,
    TypeParameterAnnotation,
    TypePrefixBool,
    TypePrefixInteger,
    TypePrefixNumeric,
    TypeRangeBinding,
    TypeRangeBounds,
    TypeRangeInteger,
    TypeRangeIterable,
    TypeReturnMismatch,
    TypeResultInferenceCycle,
    TypeReturnValue,
    TypeMethodCall,
    TypeMethodCallArity,
    TypeTextProperty,
    TypeUnresolved,
    TypeUpdateInteger,
    TypeValueRequired,
};

auto diagnostic_code_info(DiagnosticCode code) noexcept -> DiagnosticCodeInfo;

auto lookup_diagnostic_code(std::string_view name) noexcept -> std::optional<DiagnosticCode>;

auto operator==(DiagnosticCode code, std::string_view name) noexcept -> bool;
auto operator==(std::string_view name, DiagnosticCode code) noexcept -> bool;
auto operator==(DiagnosticCode code, const char* name) noexcept -> bool;
auto operator==(const char* name, DiagnosticCode code) noexcept -> bool;
