target("carven-test-support")
    set_default(false)
    set_kind("moduleonly")
    add_deps("carven-modules")
    add_files("framework.cppm", "framework.cpp")
    add_files("diagnostics.cppm", "diagnostics.cpp")
    add_files("directory.cppm", "directory.cpp")
target_end()
