target("carven-test-support")
    set_default(false)
    set_kind("moduleonly")
    add_deps("carven-modules")
    add_files("framework.cppm", "framework.cpp")
    add_files("diagnostics.cppm", "diagnostics.cpp")
    add_files("directory.cppm", "directory.cpp")
target_end()

target("carven-test-harness")
    set_default(false)
    set_kind("binary")
    add_deps("carven-test-support")
    add_files("contracts.cpp")
    add_tests("contracts", {group = "internal", run_timeout = 60000})
    on_test(function (target)
        return import("contracts", {rootdir = os.scriptdir()}).main(target)
    end)
target_end()
