target("analyzer-modules")
    set_default(false)
    set_kind("moduleonly")
    add_deps("editor-modules")
    add_files(path.join(os.scriptdir(), "src", "**.cppm"))
    add_files(path.join(os.scriptdir(), "src", "**.cpp"))
    remove_files(path.join(os.scriptdir(), "src", "analyzer.cpp"))
target_end()

target("carven-analyzer")
    set_default(false)
    set_kind("binary")
    add_deps("analyzer-modules")
    add_files(path.join(os.scriptdir(), "src", "analyzer.cpp"))
target_end()

target("analyzer-test-internal")
    set_default(false)
    set_kind("binary")
    add_deps("analyzer-modules", "carven-test-support")
    add_files(path.join(os.scriptdir(), "tests", "internal", "*.cpp"))
    add_files(path.join(os.projectdir(), "tests", "harness", "main.cpp"))
    add_tests("contracts", {group = "analyzer", run_timeout = 60000})
target_end()

target("analyzer-test-process")
    set_default(false)
    set_kind("phony")
    add_deps("carven-analyzer")
    add_tests("protocol", {group = "analyzer", run_timeout = 60000})
    on_test(function (target)
        return import("process", {rootdir = path.join(os.projectdir(), "tools", "analyzer", "tests", "process")}).main(target)
    end)
target_end()
