module;
#define DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS
#include <doctest/doctest.h>

module carven:test.internal.compiler.diagnostics.pointers;

import :test.internal.compiler.diagnostics.fixture;
import std;

TEST_CASE("Compiler diagnostics: pointer permissions and null proofs preserve source locations") {
    static constexpr auto cases = std::to_array<CompilerErrorExpectation>({
        {.name = "untyped null",
         .source = "fn invalid() { let p = nullptr; }",
         .code = "CV-TYPE-MISMATCH",
         .primary_text = "nullptr"},
        {.name = "unknown address",
         .source = "fn invalid(p: ptr<i32>) -> i32 { return *p; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*p"},
        {.name = "known null",
         .source = "fn invalid() -> i32 { let p: ptr<i32> = nullptr; return *p; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*p"},
        {.name = "immutable slot",
         .source = "fn invalid(p: ptr<&i32>) { let q = p; q = nullptr; }",
         .code = "CV-ACCESS-IMMUTABLE",
         .primary_text = "q"},
        {.name = "read target",
         .source = "fn invalid(p: ptr<i32>) { if p != nullptr { *p = 2; } }",
         .code = "CV-ACCESS-IMMUTABLE",
         .primary_text = "*p"},
        {.name = "reverse promotion",
         .source = "fn invalid(p: ptr<i32>) { let q: ptr<&i32> = p; }",
         .code = "CV-TYPE-MISMATCH",
         .primary_text = "p"},
        {.name = "target Take",
         .source = "fn invalid(p: ptr<&i32>) { if p != nullptr { let q = &&*p; } }",
         .code = "CV-ACCESS-TAKE-OPERAND",
         .primary_text = "&&"},
        {.name = "Take parameter invariant",
         .source =
             "fn sink(&&p: ptr<i32>) {} fn invalid() { var p: ptr<&i32> = nullptr; sink(&&p); }",
         .code = "CV-TYPE-MISMATCH",
         .primary_text = "&&p"},
        {.name = "unavailable address",
         .source =
             "fn invalid(p: ptr<i32>) { let owner = p; let copy = &&owner; let again = owner; }",
         .code = "CV-ACCESS-UNAVAILABLE",
         .primary_text = "owner"},
        {.name = "reassignment invalidates",
         .source =
             "fn invalid(&p: ptr<i32>, q: ptr<i32>) -> i32 { if p == nullptr { return 0; } p = q; return *p; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*p"},
        {.name = "Write invalidates",
         .source =
             "fn clear(&p: ptr<i32>) { p = nullptr; } fn invalid(&p: ptr<i32>) -> i32 { if p == nullptr { return 0; } clear(&p); return *p; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*p"},
        {.name = "aliased Write invalidates",
         .source =
             "fn invalid(&p: ptr<i32>, &q: ptr<i32>) -> i32 { if p == nullptr { return 0; } q = nullptr; return *p; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*p"},
        {.name = "one-sided branch",
         .source =
             "fn invalid(p: ptr<i32>) -> i32 { if p != nullptr { let value = *p; } return *p; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*p"},
        {.name = "wrong short circuit edge",
         .source = "fn invalid(p: ptr<i32>) -> bool { return p == nullptr && *p == 1; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*p"},
        {.name = "helper is not proof",
         .source =
             "fn valid(p: ptr<i32>) -> bool { return p != nullptr; } fn invalid(p: ptr<i32>) -> i32 { if valid(p) { return *p; } return 0; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*p"},
        {.name = "caller proof is local",
         .source =
             "fn invalid(p: ptr<i32>) -> i32 { return *p; } fn caller(p: ptr<i32>) -> i32 { if p != nullptr { return invalid(p); } return 0; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*p"},
        {.name = "loop writes clear entry proof",
         .source =
             "fn invalid(p: ptr<i32>, q: ptr<i32>) { var slot = p; if slot == nullptr { return; } while true { let value = *slot; slot = q; } }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*slot"},
        {.name = "loop condition assignments clear entry proof",
         .source =
             "fn invalid(p: ptr<i32>) { var slot = p; if slot == nullptr { return; } while (if true { let value = *slot; slot = nullptr; value > 0 } else { false }) {} }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*slot"},
        {.name = "Write capture call invalidates",
         .source =
             "fn invalid(p: ptr<i32>) -> i32 { var slot = p; let clear = [&slot]() { slot = nullptr; }; if slot == nullptr { return 0; } clear(); return *slot; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*slot"},
        {.name = "capture proof stays local",
         .source = "fn invalid(p: ptr<i32>) { if p != nullptr { let callback = [p]() => *p; } }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*p"},
        {.name = "indirect slots need snapshot",
         .source =
             "fn invalid(p: ptr<ptr<i32>>) -> i32 { if p == nullptr { return 0; } if *p != nullptr { return **p; } return 0; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "**p"},
        {.name = "dynamic index needs snapshot",
         .source =
             "fn invalid(values: [ptr<i32>; 2], i: usize) -> i32 { if values[i] != nullptr { return *values[i]; } return 0; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*values[i]"},
        {.name = "fixed index invalidated by dynamic Write",
         .source =
             "fn clear(&p: ptr<i32>) { p = nullptr; } fn invalid(&values: [ptr<i32>; 2], i: usize) -> i32 { if values[0] == nullptr { return 0; } clear(&values[i]); return *values[0]; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*values[0]"},
        {.name = "no ptr truthiness",
         .source = "fn invalid(p: ptr<i32>) { if p {} }",
         .code = "CV-TYPE-CONDITION-BOOL",
         .primary_text = "p"},
        {.name = "no ptr ordering",
         .source = "fn invalid(p: ptr<i32>, q: ptr<i32>) -> bool { return p < q; }",
         .code = "CV-TYPE-BINARY-ORDERED",
         .primary_text = "<"},
        {.name = "no ptr arithmetic",
         .source = "fn invalid(p: ptr<i32>) { let q = p + p; }",
         .code = "CV-TYPE-BINARY-NUMERIC",
         .primary_text = "+"},
        {.name = "nested permission conversion is invariant",
         .source = "fn invalid(p: ptr<&ptr<&i32>>) { let q: ptr<ptr<i32>> = p; }",
         .code = "CV-TYPE-MISMATCH",
         .primary_text = "p"},
        {.name = "aggregate covariance rejected",
         .source = "fn invalid(p: [ptr<&i32>; 1]) { let q: [ptr<i32>; 1] = p; }",
         .code = "CV-TYPE-MISMATCH",
         .primary_text = "p"},
        {.name = "mixed branch modes require context",
         .source =
             "fn invalid(p: ptr<i32>, q: ptr<&i32>, flag: bool) { let value = if flag { p } else { q }; }",
         .code = "CV-TYPE-MISMATCH",
         .primary_text = "{ q }"},
        {.name = "Write slot invariant",
         .source =
             "fn write(&p: ptr<i32>) {} fn invalid() { var p: ptr<&i32> = nullptr; write(&p); }",
         .code = "CV-TYPE-MISMATCH",
         .primary_text = "&p"},
        {.name = "void has no referent",
         .source = "fn invalid(p: ptr<void>) { if p != nullptr { let value = *p; } }",
         .code = "CV-TYPE-VALUE-REQUIRED",
         .primary_text = "*"},
        {.name = "Take target type rejected",
         .source = "fn invalid(p: ptr<&&i32>) {}",
         .code = "CV-SYNTAX",
         .primary_text = "&&"},
        {.name = "arrow dereference location",
         .source = "struct S { value: i32 } fn invalid(p: ptr<S>) -> i32 { return p->value; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "p->"},
        {.name = "test assertion is not proof",
         .source =
             "test \"invalid\" { let p: ptr<i32> = nullptr; check(p != nullptr); let value = *p; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*p"},
        {.name = "const reverse promotion",
         .source = "const p: ptr<i32> = nullptr; const q: ptr<&i32> = p;",
         .code = "CV-TYPE-MISMATCH",
         .primary_text = "p"},
        {.name = "native operand cannot enable arithmetic",
         .source = "fn invalid(p: ptr<i32>) { let q = p + ::offset; }",
         .code = "CV-TYPE-BINARY",
         .primary_text = "+"},
        {.name = "branch rebind invalidates",
         .source =
             "fn invalid(p: ptr<i32>, q: ptr<i32>, flag: bool) -> i32 { var slot = p; if slot == nullptr { return 0; } if flag { slot = q; } return *slot; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*slot"},
        {.name = "native escape invalidates subsequent calls",
         .source =
             "fn invalid(p: ptr<i32>) -> i32 { var slot = p; ::remember(&slot); if slot == nullptr { return 0; } ::touch(); return *slot; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*slot"},
        {.name = "Write helper can expose caller storage",
         .source =
             "fn remember(&p: ptr<i32>) { ::remember(&p); } fn invalid(p: ptr<i32>) -> i32 { var slot = p; remember(&slot); if slot == nullptr { return 0; } ::touch(); return *slot; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*slot"},
        {.name = "index",
         .source = "fn invalid(p: ptr<i32>) { let value = p[0]; }",
         .code = "CV-TYPE-NOT-INDEXABLE",
         .primary_text = "p[0]"},
        {.name = "integer",
         .source = "fn invalid(p: ptr<i32>) { let value = p as usize; }",
         .code = "CV-TYPE-CAST",
         .primary_text = "as"},
        {.name = "function",
         .source = "fn invalid(p: fn(ptr<i32>) -> void) { let q: fn(ptr<&i32>) -> void = p; }",
         .code = "CV-TYPE-MISMATCH",
         .primary_text = "p"},
        {.name = "mixed array",
         .source = "fn invalid(p: ptr<i32>, q: ptr<&i32>) { let value = [p, q]; }",
         .code = "CV-TYPE-MISMATCH",
         .primary_text = "q"},
        {.name = "nested branch inference does not authorize narrowing",
         .source =
             "fn invalid(p: ptr<i32>, q: ptr<&i32>, a: bool, b: bool) { let value = if a { p } else { (if b == true { q } else { p }) }; }",
         .code = "CV-TYPE-MISMATCH",
         .primary_text = "{ q }"},
        {.name = "nested array inference does not authorize narrowing",
         .source = "fn invalid(p: ptr<i32>, q: ptr<&i32>) { let value = [[p], [q]]; }",
         .code = "CV-TYPE-MISMATCH",
         .primary_text = "q"},
        {.name = "match arm inference does not authorize narrowing",
         .source =
             "fn invalid(p: ptr<i32>, q: ptr<&i32>, a: bool, b: bool) { let value = match a { true => p, false => if b { q } else { p } }; }",
         .code = "CV-TYPE-MISMATCH",
         .primary_text = "{ q }"},
        {.name = "catch inference does not authorize narrowing",
         .source =
             "struct F {} fn source(q: ptr<&i32>) -> ptr<&i32> throw F { return q; } fn invalid(p: ptr<i32>, q: ptr<&i32>, a: bool) { let value = if a { p } else { (try { source(q)? } catch { F(_) => { p } }) }; }",
         .code = "CV-TYPE-MISMATCH",
         .primary_text = "{ source(q)? }"},
        {.name = "range Write calls can expose array storage",
         .source =
             "fn invalid(p: ptr<i32>) -> i32 { var values: [ptr<i32>; 1] = [p]; for &slot in values { ::remember(&slot); } if values[0] == nullptr { return 0; } ::touch(); return *values[0]; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*values[0]"},
        {.name = "nested loop Write calls can expose array storage",
         .source =
             "fn invalid(p: ptr<i32>, flag: bool) -> i32 { var values: [ptr<i32>; 1] = [p]; while flag { for &slot in values { ::remember(&slot); } break; } if values[0] == nullptr { return 0; } ::touch(); return *values[0]; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*values[0]"},
        {.name = "field write",
         .source =
             "struct S { p: ptr<i32> } fn clear(&s: S) { s.p = nullptr; } fn invalid(&s: S) -> i32 { if s.p == nullptr { return 0; } clear(&s); return *s.p; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*s.p"},
        {.name = "failure write",
         .source =
             "struct F {} fn clear(&p: ptr<i32>) throw F { p = nullptr; throw F {}; } fn invalid(&p: ptr<i32>) -> i32 { if p == nullptr { return 0; } try { clear(&p)?; } catch { F(_) => {} } return *p; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*p"},
        {.name = "condition writes",
         .source =
             "fn clear(&p: ptr<i32>) -> bool { p = nullptr; return true; } fn invalid(&p: ptr<i32>) -> bool { return p != nullptr && clear(&p) && *p > 0; }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*p"},
        {.name = "continue writes",
         .source =
             "fn invalid(p: ptr<i32>) { var slot = p; if slot == nullptr { return; } for var i = 0; i < 2; i += 1 { if i == 1 { slot = nullptr; continue; } let value = *slot; } }",
         .code = "CV-PTR-NONNULL",
         .primary_text = "*slot"},
    });
    check_compiler_errors(cases);
}
