target("carven-test-crafts")
    set_default(false)
    set_kind("binary")
    set_languages("c++20")
    add_rules("@carven/carven", {tests = "default"})
    add_files("carven/**.cv")
    add_tests("crafts", {group = "crafts", run_timeout = 30000})
target_end()
