target("workspace-modules")
    set_default(false)
    set_kind("moduleonly")
    add_deps("carven-modules")
    add_files(path.join(os.scriptdir(), "src", "**.cppm"))
    add_files(path.join(os.scriptdir(), "src", "**.cpp"))
target_end()

target("workspace-test-internal")
    set_default(false)
    set_kind("binary")
    add_deps("workspace-modules", "carven-test-support")
    add_files(path.join(os.scriptdir(), "tests", "*.cpp"))
    add_files(path.join(os.projectdir(), "tests", "harness", "main.cpp"))
    add_tests("workspace", {group = "workspace", run_timeout = 60000})
target_end()

target("workspace-benchmark-analysis")
    set_default(false)
    set_kind("binary")
    add_deps("workspace-modules")
    add_files(path.join(os.scriptdir(), "benchmarks", "analysis.cpp"))
target_end()
